const GET_MY_FAVORITES_PENDING = "GET_MY_FAVORITES_PENDING";
const GET_MY_FAVORITES_REJECTED = "GET_MY_FAVORITES_REJECTED";
const GET_MY_FAVORITES_SUCCESS = "GET_MY_FAVORITES_SUCCESS";

const ADD_TO_FAVORITES_PENDING = "ADD_TO_FAVORITES_PENDING";
const ADD_TO_FAVORITES_REJECTED = "ADD_TO_FAVORITES_REJECTED";
const ADD_TO_FAVORITES_SUCCESS = "ADD_TO_FAVORITES_SUCCESS";

const REMOVE_FROM_FAVORITES_PENDING = "REMOVE_FROM_FAVORITES_PENDING";
const REMOVE_FROM_FAVORITES_REJECTED = "REMOVE_FROM_FAVORITES_REJECTED";
const REMOVE_FROM_FAVORITES_SUCCESS = "REMOVE_FROM_FAVORITES_SUCCESS";
