const REGISTER_USER_PENDING="REGISTER_USER_PENDING"
const REGISTER_USER_REJECTED="REGISTER_USER_REJECTED"
const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"

const LOGIN_USER_PENDING="LOGIN_USER_PENDING"
const LOGIN_USER_REJECTED="LOGIN_USER_REJECTED"
const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"